services:
   app.registration.form.type:
        class: AppBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }
   app.profile.form.type:
           class: AppBundle\Form\Type\ProfileFormType
           tags:
               - { name: form.type, alias: app_user_profile }
